# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV MLFLOW_HOME=/mlflow
ENV MLFLOW_TRACKING_URI=http://localhost:5000

# Expose the port the app runs on
EXPOSE 8080

# Run the command to start MLflow server when the container launches
CMD ["mlflow", "server", "--host", "0.0.0.0"]
